name: Build binaries

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      release_mode:
        description: 'Release Mode'
        required: true
        default: 'draft'
        type: choice
        options:
        - draft
        - prerelease
        - full

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container: devkitpro/devkitppc:20260503
    timeout-minutes: 20
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js for act compatibility
        if: ${{ env.ACT == 'true' }}
        run: |
          apt-get update
          apt-get install -y nodejs
          echo ${{ env.ACT }}

      - name: Add safe directory exception for git inside the container
        run: |
          git config --global --add safe.directory $(pwd)

      - name: Compile
        run: |
          make -j$(nproc)

      - name: Package
        run: |
          cp -r wii/apps apps
          mkdir -p apps/wiiflorked/
          cp -r out/bins apps/wiiflorked/bins
          cp -r out/imgs apps/wiiflorked/imgs
          cp out/boot.dol apps/wiiflorked/
          mv apps/wiiflow/* apps/wiiflorked/
          rm -rf apps/wiiflow
          mkdir -p wiiflow
          cp -r wii/wiiflow/Languages wiiflow/languages
          cp -r wii/wiiflow/themes_lite wiiflow/themes_lite
        
          echo "sha=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with: 
          name: wiiflorked_${{ env.sha }}
          path: |
            apps
            wiiflow

      - name: Zip release payload
        if: ${{ env.ACT != 'true' }}
        run: |
          apt-get update && apt-get install -y zip curl
          zip -r wiiflorked_${{ env.sha }}.zip apps wiiflow

      - name: Create Release
        if: ${{ env.ACT != 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # set -x
          
          curl -sSL https://github.com/cli/cli/releases/download/v2.49.0/gh_2.49.0_linux_amd64.tar.gz | tar xz -C /tmp
          mv /tmp/gh_2.49.0_linux_amd64/bin/gh /usr/local/bin/
          
          FLAGS=""
          
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            if [ "${{ inputs.release_mode }}" = "draft" ]; then
              FLAGS="--draft"
            elif [ "${{ inputs.release_mode }}" = "prerelease" ]; then
              FLAGS="--prerelease"
            fi
          fi

          if gh release view build-${{ env.sha }} >/dev/null 2>&1; then
            echo "Release build-${{ env.sha }} already exists. Editing..."
            gh release edit build-${{ env.sha }} $FLAGS
          else
            echo "Creating new release..."
            gh release create build-${{ env.sha }} wiiflorked_${{ env.sha }}.zip --title "Build ${{ env.sha }}" --generate-notes $FLAGS
          fi